### ISSUE TITLE
Losing Steps, Pulse Width>?

### ISSUE THREAD

**Issue by Ritzy22** [grbl/grbl#1443] opened 2018-10-06 00:57 UTC
Hi,

**Step pulses occasionally are longer, causing lost steps??**

I have had an issue with inconsistent probe depths  (probing the exact same spot multiple times) seeing variation from + or -0.004-0.028mm. 

This issue is reduced significantly when 5 microstepping vs 10 microstepping however, it still occurs and i suspect it is due to there being half the number of steps required.

I have replace the UNO with a mega (both clones) as the UNO was using the CH340G chip and that seemed to help a bit however still plagues the 10 microstep making it unusable. I have also tried to reduce noise as much as possible screening all signal wires, strong pullups, screened USB cable and using my bench top power supply to no avail.

Looking at the step pulses it seems that occasionally they may vary in length getting longer (link)?

https://imgur.com/a/OjcnkzM

This occurs no matter what the pulse width is.

Is there something i'm missing???
Any help would be greatly appreciated :)

**note:** using the Geckodrive 213V

**Comment by chamnit** [comment] 2018-10-06 01:27
Duplicate of https://github.com/gnea/grbl-Mega/issues/76. Closing.

**Closed by chamnit** 2018-10-06 01:27 UTC
